version: '3.4'

services:
    chromedriver:
        image: selenium/standalone-chrome
        ports: 
            - "4444:4444"
    seleniumtests:
        image: seleniumtests
        build:
            context: .
            dockerfile: dockerfile
        entrypoint:
            - dotnet
            - test